#
# Makefile for tfa9891 smartamp driver.
#

#debugging support (also enables trace_printk)
#CFLAGS += -DDEBUG
#CFLAGS += -Werror

snd-soc-tfa98xx-objs += tfa98xx.o
snd-soc-tfa98xx-objs += tfa_container.o
snd-soc-tfa98xx-objs += tfa_dsp.o
snd-soc-tfa98xx-objs += tfa_init.o
snd-soc-tfa98xx-objs += tfa_debug.o

obj-$(CONFIG_SND_SOC_TFA98XX) += snd-soc-tfa98xx.o
